---
title: "Multivariate Verfahren"
author: "Janika Saretzki"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook: 
    css: null
    split_by: chapter
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: ""
delete_merged_file: true
---


# Über dieses Skript {-}

Liebe Studierende,

dieses Skript soll Sie in die Grundlagen der multivariaten Verfahren einführen. Im Gegensatz zu univariaten Ansätzen, die nur eine abhängige Variable betrachten, erlauben multivariate Verfahren die gleichzeitige Analyse mehrerer Variablen. Dadurch können Zusammenhänge und Wechselwirkungen zwischen Variablen besser erfasst werden, was zu umfassenderen und realistischeren Modellen führt.

Multivariate Verfahren sind besonders nützlich, wenn es darum geht, die gleichzeitige Wirkung mehrerer Einflussfaktoren auf mehrere Ergebnisvariablen zu untersuchen. Sie bieten auch Fit-Maße, die die Modellgüte sowohl auf Gesamt- als auch auf Teilmodellebene bewerten. Diese liefern detaillierte Informationen darüber, wie gut das Modell zu den Daten passt und wo Optimierungsbedarf besteht.

Trotz der höheren Anforderungen, insbesondere an die Stichprobengröße und die komplexere Interpretation, sind multivariate Verfahren unverzichtbar für die realitätsnahe Modellierung komplexer Phänomene. Dieses Skript wird Sie durch die wesentlichen Konzepte und Methoden führen, um Ihnen den Einstieg zu erleichtern.

Wir wünschen Ihnen viel Erfolg und Spaß beim Arbeiten mit diesen Methoden!
